var geojsonObject = {
"type": "FeatureCollection",
"name": "KoirapuistotJSON",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Id": "1", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.26214, 60.48565 ] } },
{ "type": "Feature", "properties": { "Id": "2", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.2538, 60.47573 ] } },
{ "type": "Feature", "properties": { "Id": "3", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.35913, 60.40451 ] } },
{ "type": "Feature", "properties": { "Id": "Hirvensalon koirapuisto", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.21094, 60.41579 ] } },
{ "type": "Feature", "properties": { "Id": "Härkähaan koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.1967, 60.46841 ] } },
{ "type": "Feature", "properties": { "Id": "Piikkiön koirapuisto", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.50422, 60.43099 ] } },
{ "type": "Feature", "properties": { "Id": "7", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.29774, 60.43134 ] } },
{ "type": "Feature", "properties": { "Id": "Iso-Heikkilänpuiston koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.22425, 60.45069 ] } },
{ "type": "Feature", "properties": { "Id": "9", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.37542, 60.45779 ] } },
{ "type": "Feature", "properties": { "Id": "Lausteen Koirapuisto", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.35217, 60.43304 ] } },
{ "type": "Feature", "properties": { "Id": "Nummenrannan koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.29595, 60.46525 ] } },
{ "type": "Feature", "properties": { "Id": "Marjavuoren koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.35213, 60.44439 ] } },
{ "type": "Feature", "properties": { "Id": "Laivanrakentajanpuiston koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.15956, 60.45076 ] } },
{ "type": "Feature", "properties": { "Id": "Kupittaan Koirapuisto", "Koko": "Eroteltu alue suurille/pienille koirille", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.29935, 60.44567 ] } },
{ "type": "Feature", "properties": { "Id": "15", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.26177, 60.4252 ] } },
{ "type": "Feature", "properties": { "Id": "16", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.3582, 60.53674 ] } },
{ "type": "Feature", "properties": { "Id": "Jääpuisto dog park", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.26962, 60.43067 ] } },
{ "type": "Feature", "properties": { "Id": "Jyrkkälänmäen koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.20425, 60.46034 ] } },
{ "type": "Feature", "properties": { "Id": "Fleminginpuiston koira-aitaus", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.25049, 60.43615 ] } },
{ "type": "Feature", "properties": { "Id": "20", "Koko": "Viheralue / Yleiset", "Varusteryhma_koodi": 4, "Varustelaji": "Koira-aitaus", "Varustelaji_koodi": "T_283", "SijainninKuvaus": null }, "geometry": { "type": "Point", "coordinates": [ 22.24897, 60.44413 ] } }
]
}
